- name: grant password-less sudo to "sebastien" user
  become: true
  copy:
    content: |
      sebastien ALL=(ALL:ALL) NOPASSWD: ALL
    dest: "/etc/sudoers.d/sebastien"
    mode: "0440"

- name: Install packages
  ansible.builtin.include_tasks: packages.yaml

- name: Set ZSH as default shell
  ansible.builtin.include_tasks: zsh.yaml
  when: "'zsh' not in ansible_env.SHELL"

- name: Check if doom is installed
  stat:
    path: ~/.doom.d
  register: is_doom

- name: Install Doom emacs
  ansible.builtin.include_tasks: doom.yaml
  when: is_doom.stat.exists == False

- name: Check if install is needed
  shell: cat /usr/share/X11/xkb/symbols/us
  register: us_layout
  check_mode: False
  tags: qwerty

- name: Install qwerty-fr
  ansible.builtin.include_tasks: qwerty-fr.yaml
  when: "us_layout.stdout.find('qwerty-fr') == -1"
  tags: qwerty

- name: Install fonts
  ansible.builtin.include_tasks: fonts.yaml
