- name: grant password-less sudo to "sebastien" user
  become: true
  copy:
    content: |
      sebastien ALL=(ALL:ALL) NOPASSWD: ALL
    dest: "/etc/sudoers.d/sebastien"
    mode: "0440"

- name: Install packages
  become: True
  include: packages.yaml

- name: Set ZSH as default shell
  become: true
  include: zsh.yaml
  when: "'zsh' not in ansible_env.SHELL"

- name: Install Doom emacs
  include: doom.yaml
  when: is_doom.stat.exists == False

- name: Install qwerty-fr
  become: true
  include: qwerty-fr.yaml
  when: "us_layout.stdout.find('qwerty-fr') == -1"
  tags: qwerty

- name: Install fonts
  include: fonts.yaml
  notify: regen-font-cache
