- name: Enable rpmfusion
  dnf:
    name: "{{ fusion }}"
  become: true

- name: Base packages install
  dnf:
    name: "{{ packages }}"
    state: latest
  become: true

- name: Add the flathub flatpak repository remote to the user installation
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: system
  become: true

- name: Install flatpak
  flatpak:
    name: "{{ item }}"
    state: present
    method: system
  loop: "{{ flatpaks }}"
  become: true
