# qwerty-fr layout
- set_fact:
    evdev_xml: |
     <?xml version="1.0" encoding="UTF-8"?>
     <!DOCTYPE xkbConfigRegistry SYSTEM "xkb.dtd">
     <xkbConfigRegistry version="1.1">
       <layoutList>
         <layout>
           <configItem>
             <name>us_qwerty-fr</name>
             <shortDescription>English (US, qwerty-fr)</shortDescription>
             <description>English (US, qwerty-fr)</description>
           </configItem>
         </layout>
       </layoutList>
     </xkbConfigRegistry>

- set_fact:
    evdev_lst: |
     ! layout
     us_qwerty-fr  English (US, qwerty-fr)

- name: Download qwerty-fr layout
  ansible.builtin.git:
    repo: git@github.com:qwerty-fr/qwerty-fr.git
    dest: "{{ home }}/git/"

- name: Make directories in .config
  ansible.builtin.file:
    path: "{{ home }}/.config/xkb/{{ item }}"
    state: directory
  loop:
    - symbols
    - rules

- name: copy symbols
  ansible.builtin.copy:
    src: "{{ home }}/git/qwerty-fr/linux/us_qwerty-fr"
    dest: "{{ home }}/.config/symbols/"

- ansible.builtin.copy:
    content: "{{ item }}"
    dest: "{{ home }}/.config/rules/{{ item | regex_replace('\\_', '\\.') }}"
  loop:
    - evdev_xml
    - evdev_lst
