- name: Rebuild kernel module
  shell: akmods --force
  listen: rebuild kernel module

- name: Rebuild initramfs
  shell: dracut --force
  listen: rebuild initramfs

- name: tell user when reboot is needed
  debug: msg="reboot needed !!!"
  listen: should reboot
  when: '"reboot" not in ansible_run_tags'
  changed_when: true

- name: reboot server
  listen: should reboot
  reboot:
  when: '"reboot" in ansible_run_tags'
